FROM python:3.11-slim

WORKDIR /app

COPY streamlit_requirements.txt /app/streamlit_requirements.txt
RUN pip install --no-cache-dir -r streamlit_requirements.txt

COPY ./frontend /app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
